#!/usr/bin/env python

import re
import sys

if(len(sys.argv) < 2):
    print("\nyou need to input argument\n")
    sys.exit()

current_file = sys.argv[1]

def print_script_like_comment():
    print("# ")
    print("# ")
    print("# ")
    print("# ")

def print_html_comment():
    print("<!--")
    print("  --")
    print("  --")
    print("  --")
    print("  -->")

def print_normal_comment():
    print("// ")
    print("// ")
    print("// ")
    print("// ")
    print("// ")

def read_first_line(current_file):
    file = open(current_file)
    line = file.readline()
    file.close()
    return line

first_line = read_first_line(current_file)

#
# detect html here
#
if(re.search(r"[^.]+\.html$", current_file)):
    print_html_comment()

#
# detect bash|sh|ruby|python here
#
elif(
    re.search(r"[^.]+\.(sh|rb|py)",                      current_file) or
    re.search(r"#!/usr/bin/env\s+(sh|bash|ruby|python)", first_line  )
):
    print_script_like_comment()

#
# detect groovy|java|C# here
#
elif(
    re.search(r"[^.]+\.(groovy|java)",           current_file) or
    re.search(r"#!/usr/bin/env\s+(groovy|java)", first_line  )
):
    print_normal_comment()

else:
    print("corresponding file for " + current_file + " not found.")
